name:Test GitHub Action

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on:ubuntu-latest

    steps: 
      -name:Checkout repo
       uses: actions/checkout@v3

      -name: Say Hello
        run: echo"GitHub Actions is running!"

