name: Update Machine Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-machine-data:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      # 4️⃣ Run your converter
      - name: Run converter
        run: python src/converter.py

      # 5️⃣ Commit and push the updated machineData.js
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update machineData.js"
          branch: main
          file_pattern: js/machineData.js
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: mzzgitthub <41898282+github-actions[bot]@users.noreply.github.com>
          push_options: --force
          repository: https://mzzgitthub:${{ secrets.GH_PAT }}@github.com/mzzgitthub/machine-tracker.git