name: Update Machine Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      # 4️⃣ Run converter.py
      - name: Run converter
        run: python src/converter.py

      # 5️⃣ Commit & push machineData.js
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update machineData.js"
          branch: main
          file_pattern: js/machineData.js
          github_token: ${{ secrets.GH_PATH }}